### ISSUE TITLE
"評比績效指標"的意思

### ISSUE THREAD

**Issue by leo08260826** [leo08260826/Fintech_HW#1]
指標是指針對甚麼指標?
績效是什麼意思啊OAO?

**Comment by leo08260826** [comment]
ETF是基金嗎?

**Comment by yac7447** [comment]
投資人要在市場上一堆基金裡面選好的基金來投資，會需要一些績效指標來協助判斷好壞。
以往比較經典的指標是 sharpe ratio ，這是說投資人承擔一單位的總風險可以得到多少超額報酬。
但老師上課時說明這個指標過時，沒有考慮到投資人對風險的偏好，所以他講了R指標、OMEGA，並希望我們研究文獻看有沒有更新更好的。
